---
  - name: Download of elasticsearch
    tags: CentOS
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.4.3-x86_64.rpm
      dest: /tmp/elasticsearch-8.4.3-x86_64.rpm

  - name: Installing elasticsearch
    tags: CentOS
    yum:
      name: /tmp/elasticsearch-8.4.3-x86_64.rpm
      state: present

  - name: Enable and start ElasticSearch service
    service:
      name: elasticsearch
      enabled: yes
      state: started

  - name: Download of kibana
    rpm_key:
      state: present
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

  - name: Adding kibana to rpm repository
    copy:
      src: kibana.repo
      dest: /etc/yum.repos.d/kibana.repo
      owner: root
      group: root
      mode: 777

  - name: Update repository for kibana
    yum:
      name:
        - kibana
      state: latest

  - name: Opening port for Kibana
    firewalld:
      port: 5601/tcp
      zone: public
      permanent: yes
      state: enabled

  - name: Enable and start Kibana Service
    service:
      name: kibana
      enabled: true
      state: restarted

  - name: Download and Installing public signing key
    tags: CentOS
    rpm_key:
      state: present
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

  - name: Creating a repo file for Logstash
    tags: CentOS
    copy:
      src: logstash.repo
      dest: /etc/yum.repos.d/logstash.repo
      owner: root
      group: root
      mode: 0777

  - name: Update repo
    dnf:
      update_cache: yes

  - name: Installing logstash
    dnf:
      name:
        - logstash
      state: latest

  - name: Opening port for Logstash
    shell: |
      sudo firewall-cmd --permanent --zone=public --add-port=9600/tcp
      sleep 10
      sudo firewall-cmd --reload

  - name: Enable and Start Logstash service
    service:
      name: logstash
      enabled: yes
      state: started
