---
  - hosts: all
   become: true
   pre_tasks:

  - name: Installing dnf and epel-release
    yum:
      name:
        - epel-release
        - dnf
    when: ansible_distribution == "CentOS"

  - name: Update and Upgrade (CentOS)
    dnf:
      update_cache: yes
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Update and Upgrade (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - hosts: Ubuntu
    become: true
    roles:
      - Ubuntu

  - hosts: CentOS
    become: true
    roles:
      - CentOS
