---
  - name: Installation of dependencies
    apt:
      name:
        - apt-transport-https
        - openjdk-8-jdk
        - software-properties-common
        - wget
      state: latest

  - name: Download of elasticsearch
    tags: CentOS
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.4.3-amd64.deb
      dest: /tmp/elasticsearch-8.4.3-amd64.deb

  - name: Installing elasticsearch
    apt:
      name: /tmp/elasticsearch-8.4.3-amd64.deb

  - name: Enable and start ElasticSearch service
    service:
      name: elasticsearch
      enabled: yes
      state: started

  - name: Starting and Enabling the daemon
    shell: |
      sudo systemctl enable elasticsearch.service
      sleep 10
      sudo systemctl start elasticsearch.service
    ignore_errors: yes

  - name: Download of kibana
    get_url: https://artifacts.elastic.co/downloads/kibana/kibana-8.4.3-amd64.deb
    dest: /tmp/kibana-8.4.3-amd64.deb

  - name: Installing kibana
    apt:
      deb: /tmp/kibana-8.4.3-amd64.deb

  - name: Reloading of daemon
    command: /bin/systemctl daemon-reload

  - name: Enable and start Kibana Service
    service:
      name: kibana
      enabled: true
      state: restarted

  - name: Downloading of logstash
    get_url:
      url: https://artifacts.elastic.co/downloads/logstash/logstash-8.4.3-amd64.deb
      dest: /tmp/logstash-8.4.3-amd64.deb

  - name: Installing logstash
    apt:
      deb: /tmp/logstash-8.4.3-amd64.deb

  - name: Reloading of daemon
    command: /bin/systemctl daemon-reload

  - name: Enable and Start Logstash service
    service:
      name: logstash
      enabled: yes
      state: started
